In [2]:
import os
import pandas as pd
from deta import Deta
from dotenv import load_dotenv

load_dotenv()

deta = Deta(os.environ.get("DETA_PROJECT_KEY"))

drive = deta.Drive("data")

In [37]:
current_df = pd.read_csv('https://drive.deta.sh/v1/b0x22rtxtdf/data/files/download?name=current.csv', storage_options={'X-API-Key':os.environ.get("DETA_PROJECT_KEY")})
current_df.ds = pd.to_datetime(current_df.ds)
current = current_df.head(1).iloc[0]
current

ds                     2023-11-29 15:00:00
INFLOW_STRETCHER                        12
Infl_Stretcher_cum                     100
INFLOW_AMBULATORY                       14
Infl_Ambulatory_cum                     63
Inflow_Total                            26
Inflow_Cum_Total                       163
INFLOW_AMBULANCES                        4
Infl_Ambulances_cum                     29
FLS                                      1
CUM_ADMREQ                              17
CUM_BA1                                  5
WAITINGADM                              51
TTStr                                  136
TRG_HALLWAY1                             8
TRG_HALLWAY_TBS                          7
reoriented_cum                          21
reoriented_cum_MD                        0
QTRACK1                                  8
RESUS                                    5
Pod_T                                   52
POD_GREEN                               18
POD_GREEN_TBS                            1
POD_YELLOW                              17
POD_YELLOW_TBS                           3
POD_ORANGE                              17
POD_ORANGE_TBS                           0
POD_CONS_MORE2H                         10
POD_IMCONS_MORE4H                        0
POD_XRAY_MORE2H                          0
POD_CT_MORE2H                            0
POST_POD1                               14
VERTSTRET                               33
RAZ_TBS                                  4
RAZ_LAZYBOY                              9
RAZ_WAITINGREZ                          10
AMBVERT1                                20
AMBVERTTBS                              15
QTrack_TBS                               6
Garage_TBS                               0
RAZ_CONS_MORE2H                          8
RAZ_IMCONS_MORE4H                        1
RAZ_XRAY_MORE2H                          1
RAZ_CT_MORE2H1                           5
PSYCH1                                  24
PSYCH_WAITINGADM                        18
Name: 0, dtype: object

In [38]:
df = current_df.copy()

In [39]:
current_ds = current.ds
current_ds

Timestamp('2023-11-29 15:00:00')

In [40]:
current_ds - pd.Timedelta(hours=current_ds.hour)

Timestamp('2023-11-29 00:00:00')

In [44]:
yesterday_total_inflow = current_df.set_index('ds').loc[current.ds - pd.Timedelta(hours=current_ds.hour)].Inflow_Cum_Total
yesterday_total_inflow

263

In [47]:
yesterday_ambulances = current_df.set_index('ds').loc[current.ds - pd.Timedelta(hours=current_ds.hour)].Infl_Ambulances_cum
yesterday_ambulances

42

In [48]:
yesterday_reorientations = current_df.set_index('ds').loc[current.ds - pd.Timedelta(hours=current_ds.hour)].reoriented_cum
yesterday_reorientations

31

In [46]:
current_df.set_index('ds').loc[current.ds - pd.Timedelta(hours=current_ds.hour)]

INFLOW_STRETCHER         0
Infl_Stretcher_cum     118
INFLOW_AMBULATORY        2
Infl_Ambulatory_cum    145
Inflow_Total             2
Inflow_Cum_Total       263
INFLOW_AMBULANCES        0
Infl_Ambulances_cum     42
FLS                      0
CUM_ADMREQ              41
CUM_BA1                 30
WAITINGADM              47
TTStr                   89
TRG_HALLWAY1             0
TRG_HALLWAY_TBS          0
reoriented_cum          31
reoriented_cum_MD       17
QTRACK1                  1
RESUS                    5
Pod_T                   47
POD_GREEN               16
POD_GREEN_TBS            1
POD_YELLOW              14
POD_YELLOW_TBS           1
POD_ORANGE              17
POD_ORANGE_TBS           1
POD_CONS_MORE2H         20
POD_IMCONS_MORE4H        1
POD_XRAY_MORE2H          2
POD_CT_MORE2H            2
POST_POD1                5
VERTSTRET               11
RAZ_TBS                  0
RAZ_LAZYBOY              5
RAZ_WAITINGREZ          13
AMBVERT1                32
AMBVERTTBS              24
QTrack_TBS               1
Garage_TBS               0
RAZ_CONS_MORE2H          6
RAZ_IMCONS_MORE4H        0
RAZ_XRAY_MORE2H          0
RAZ_CT_MORE2H1           2
PSYCH1                  21
PSYCH_WAITINGADM        17
Name: 2023-11-29 00:00:00, dtype: int64

In [61]:
current_df.set_index('ds').resample("D").max()

,INFLOW_STRETCHER,Infl_Stretcher_cum,INFLOW_AMBULATORY,Infl_Ambulatory_cum,Inflow_Total,Inflow_Cum_Total,INFLOW_AMBULANCES,Infl_Ambulances_cum,FLS,CUM_ADMREQ,...,AMBVERT1,AMBVERTTBS,QTrack_TBS,Garage_TBS,RAZ_CONS_MORE2H,RAZ_IMCONS_MORE4H,RAZ_XRAY_MORE2H,RAZ_CT_MORE2H1,PSYCH1,PSYCH_WAITINGADM
ds,,,,,,,,,,,,,,,,,,,,,
2023-11-28,16,118,15,143,24,261,5,42,2,41,...,44,34,4,0,11,0,1,7,21,17
2023-11-29,19,118,14,145,26,263,7,42,1,41,...,32,24,6,0,13,1,2,5,24,19

In [72]:
import datetime
yesterday = current_df.ds.max().date() - datetime.timedelta(days=1)
yesterday = pd.to_datetime(yesterday)

In [88]:
yesterday_df = current_df[(current_df.ds >= yesterday) & (current_df.ds < current_ds - pd.Timedelta(hours=current_ds.hour))
].set_index('ds')

In [91]:
yesterday_df.loc[yesterday_df.idxmax().TRG_HALLWAY1]

INFLOW_STRETCHER         8
Infl_Stretcher_cum      61
INFLOW_AMBULATORY       13
Infl_Ambulatory_cum     63
Inflow_Total            21
Inflow_Cum_Total       124
INFLOW_AMBULANCES        1
Infl_Ambulances_cum     21
FLS                      2
CUM_ADMREQ              10
CUM_BA1                  7
WAITINGADM              42
TTStr                  123
TRG_HALLWAY1             9
TRG_HALLWAY_TBS          9
reoriented_cum          15
reoriented_cum_MD        3
QTRACK1                  6
RESUS                    3
Pod_T                   53
POD_GREEN               21
POD_GREEN_TBS            2
POD_YELLOW              16
POD_YELLOW_TBS           3
POD_ORANGE              16
POD_ORANGE_TBS           0
POD_CONS_MORE2H          8
POD_IMCONS_MORE4H        0
POD_XRAY_MORE2H          0
POD_CT_MORE2H            2
POST_POD1                8
VERTSTRET               31
RAZ_TBS                  8
RAZ_LAZYBOY              8
RAZ_WAITINGREZ           7
AMBVERT1                11
AMBVERTTBS               6
QTrack_TBS               2
Garage_TBS               0
RAZ_CONS_MORE2H          7
RAZ_IMCONS_MORE4H        0
RAZ_XRAY_MORE2H          0
RAZ_CT_MORE2H1           1
PSYCH1                  19
PSYCH_WAITINGADM        14
Name: 2023-11-28 13:00:00, dtype: int64

In [85]:
yesterday_df

,ds,INFLOW_STRETCHER,Infl_Stretcher_cum,INFLOW_AMBULATORY,Infl_Ambulatory_cum,Inflow_Total,Inflow_Cum_Total,INFLOW_AMBULANCES,Infl_Ambulances_cum,FLS,...,AMBVERT1,AMBVERTTBS,QTrack_TBS,Garage_TBS,RAZ_CONS_MORE2H,RAZ_IMCONS_MORE4H,RAZ_XRAY_MORE2H,RAZ_CT_MORE2H1,PSYCH1,PSYCH_WAITINGADM
16,2023-11-28 23:00:00,5,118,0,143,5,261,2,42,1,...,38,27,1,0,3,0,0,4,21,17
17,2023-11-28 22:00:00,2,113,5,143,7,256,2,40,0,...,44,33,1,0,2,0,0,7,21,16
18,2023-11-28 21:00:00,2,111,7,138,9,249,1,38,0,...,43,34,1,0,4,0,0,4,21,16
19,2023-11-28 20:00:00,8,109,7,131,15,240,4,37,1,...,36,29,1,0,4,0,0,2,21,15
20,2023-11-28 19:00:00,5,101,15,124,20,225,3,33,0,...,37,29,1,0,7,0,0,2,19,14
21,2023-11-28 18:00:00,4,96,8,109,12,205,2,30,0,...,23,18,1,0,5,0,1,1,19,13
22,2023-11-28 17:00:00,4,92,11,101,15,193,0,28,0,...,24,20,4,0,7,0,1,4,19,13
23,2023-11-28 16:00:00,7,88,5,90,12,178,2,28,0,...,23,19,2,0,11,0,0,5,20,13
24,2023-11-28 15:00:00,11,81,9,85,20,166,1,26,0,...,20,16,2,0,6,0,0,3,20,13
25,2023-11-28 14:00:00,9,70,13,76,22,146,4,25,0,...,11,7,4,0,5,0,0,2,20,13
26,2023-11-28 13:00:00,8,61,13,63,21,124,1,21,2,...,11,6,2,0,7,0,0,1,19,14
27,2023-11-28 12:00:00,16,53,8,50,24,103,4,20,0,...,15,8,1,0,9,0,0,0,19,15
28,2023-11-28 11:00:00,13,37,7,42,20,79,3,16,0,...,16,8,1,0,9,0,0,0,17,15
29,2023-11-28 10:00:00,6,24,9,35,15,59,5,13,0,...,12,6,1,0,9,0,0,0,18,16

In [74]:
yesterday_peaks_df = current_df.set_index('ds').resample("D").max().loc[yesterday]
yesterday_peaks_df

INFLOW_STRETCHER        16
Infl_Stretcher_cum     118
INFLOW_AMBULATORY       15
Infl_Ambulatory_cum    143
Inflow_Total            24
Inflow_Cum_Total       261
INFLOW_AMBULANCES        5
Infl_Ambulances_cum     42
FLS                      2
CUM_ADMREQ              41
CUM_BA1                 30
WAITINGADM              47
TTStr                  127
TRG_HALLWAY1             9
TRG_HALLWAY_TBS          9
reoriented_cum          31
reoriented_cum_MD       17
QTRACK1                 10
RESUS                    6
Pod_T                   55
POD_GREEN               22
POD_GREEN_TBS            5
POD_YELLOW              18
POD_YELLOW_TBS           6
POD_ORANGE              18
POD_ORANGE_TBS           2
POD_CONS_MORE2H         14
POD_IMCONS_MORE4H        3
POD_XRAY_MORE2H          1
POD_CT_MORE2H            4
POST_POD1               13
VERTSTRET               34
RAZ_TBS                  8
RAZ_LAZYBOY             11
RAZ_WAITINGREZ          12
AMBVERT1                44
AMBVERTTBS              34
QTrack_TBS               4
Garage_TBS               0
RAZ_CONS_MORE2H         11
RAZ_IMCONS_MORE4H        0
RAZ_XRAY_MORE2H          1
RAZ_CT_MORE2H1           7
PSYCH1                  21
PSYCH_WAITINGADM        17
Name: 2023-11-28 00:00:00, dtype: int64

In [76]:
yesterday_peak_prepod = yesterday_peaks_df.TRG_HALLWAY1
yesterday_peak_prepod

9

In [77]:
yesterday_peak_family_room = yesterday_peaks_df.POST_POD1
yesterday_peak_family_room

13